apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: elearning-ingress
    namespace: ingress
spec:
    ingressClassName: nginx
    rules:
        - host: api-elearning.novalearn.id.vn
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: external-clusterip-api
                            port:
                                number: 3000
