apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: elearning-ingress
    namespace: ingress
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
    ingressClassName: nginx
    tls:
        - hosts:
              - api-elearning.novalearn.id.vn
          secretName: elearning-tls
    rules:
        - host: api-elearning.novalearn.id.vn
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: external-clusterip-api
                            port:
                                number: 3000
