apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: transcode
    name: job-manager
rules:
    - apiGroups: ["batch"]
      resources: ["jobs"]
      verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: job-manager-binding
    namespace: transcode
subjects:
    - kind: ServiceAccount
      name: default
      namespace: transcode
roleRef:
    kind: Role
    name: job-manager
    apiGroup: rbac.authorization.k8s.io
