apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/KhoiMaiDinh/ELearning_Infrastructure.git
        targetRevision: HEAD
        path: prod
        directory:
            recurse: true
    destination:
        server: https://kubernetes.default.svc
        namespace: nova-learn

    syncPolicy:
        syncOptions:
            - CreateNamespace=true

        automated:
            prune: true
            selfHeal: true
