apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafdrop
    labels:
        app: kafdrop
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafdrop
    template:
        metadata:
            labels:
                app: kafdrop
        spec:
            containers:
                - name: kafdrop
                  image: obsidiandynamics/kafdrop:latest
                  ports:
                      - containerPort: 9000
                  env:
                      - name: KAFKA_BROKERCONNECT
                        value: "your-kafka-service:9092" # 🔁 Replace with your Kafka service name
