apiVersion: v1
kind: Service
metadata:
    name: redpanda
    namespace: infra
spec:
    selector:
        app: redpanda
    ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
