apiVersion: v1
kind: Service
metadata:
    name: redpanda
    namespace: infra
    labels:
        app: redpanda
spec:
    type: ClusterIP
    selector:
        app: redpanda
    ports:
        - name: kafka
          port: 9092
          targetPort: 9092
        - name: rpc
          port: 33145
          targetPort: 33145
