apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: redpanda
    namespace: infra
    labels:
        app: redpanda
spec:
    serviceName: "redpanda"
    replicas: 1
    selector:
        matchLabels:
            app: redpanda
    template:
        metadata:
            labels:
                app: redpanda
        spec:
            containers:
                - name: redpanda
                  image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
                  securityContext:
                      runAsUser: 0
                  args: [
                          "redpanda",
                          "start",
                          "--smp",
                          "1",
                          "--memory",
                          "512Mi",
                          "--overprovisioned",
                          "--check=false",
                      ] # minimal resource flags
                  ports:
                      - name: kafka
                        containerPort: 9092
                      - name: rpc
                        containerPort: 33145
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/redpanda/data
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 5Gi
